# Generated by Django 2.1.1 on 2018-09-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='artist',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
